# Generated by Django 5.0.1 on 2026-01-21 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry_date", models.DateField()),
                ("strike", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "option_type",
                    models.CharField(
                        choices=[("PUT", "Put"), ("CALL", "Call")], max_length=4
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ask",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "last",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("volume", models.IntegerField(default=0)),
                ("open_interest", models.IntegerField(default=0)),
                (
                    "implied_volatility",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "gamma",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "theta",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "vega",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["stock", "expiry_date", "strike"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                (
                    "beta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("free_cash_flow", models.BigIntegerField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="UserConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_dte",
                    models.IntegerField(
                        default=7, help_text="Minimum days to expiration"
                    ),
                ),
                (
                    "max_dte",
                    models.IntegerField(
                        default=45, help_text="Maximum days to expiration"
                    ),
                ),
                (
                    "min_delta",
                    models.DecimalField(decimal_places=2, default=-0.38, max_digits=3),
                ),
                (
                    "max_delta",
                    models.DecimalField(decimal_places=2, default=-0.2, max_digits=3),
                ),
                (
                    "max_iv",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.29,
                        help_text="Max implied volatility",
                        max_digits=4,
                    ),
                ),
                (
                    "min_premium_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Min premium %",
                        max_digits=4,
                    ),
                ),
                (
                    "min_roe",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Min ROE %",
                        max_digits=4,
                    ),
                ),
                (
                    "max_position_size",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=10),
                ),
                (
                    "max_loss_per_trade",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("notification_email", models.EmailField(blank=True, max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Configuration",
                "verbose_name_plural": "User Configurations",
            },
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(default="CASH_SECURED_PUT", max_length=20),
                ),
                ("premium", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "err_pct",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Expected Rate of Return %",
                        max_digits=5,
                    ),
                ),
                (
                    "apy_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annualized Percentage Yield",
                        max_digits=5,
                    ),
                ),
                ("break_even", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_loss_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="ibkr.option",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="ibkr.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddField(
            model_name="option",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="ibkr.stock",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="option",
            unique_together={("stock", "expiry_date", "strike", "option_type")},
        ),
    ]
