# Generated by Django 5.0.1 on 2026-01-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="avg_volume",
            field=models.BigIntegerField(
                blank=True, help_text="Average Volume", null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="dividend_yield",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Dividend Yield %",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="fifty_two_week_high",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="fifty_two_week_low",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="forward_pe",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Forward P/E Ratio",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="pe_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price to Earnings Ratio",
                max_digits=8,
                null=True,
            ),
        ),
    ]
