# Generated by Django 5.0.1 on 2026-01-22 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0002_stock_avg_volume_stock_dividend_yield_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockIndicator",
            fields=[
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="indicators",
                        serialize=False,
                        to="ibkr.stock",
                    ),
                ),
                (
                    "rsi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="RSI (14-period)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "rsi_signal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OVERSOLD", "Oversold < 30"),
                            ("NEUTRAL", "Neutral 30-70"),
                            ("OVERBOUGHT", "Overbought > 70"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ema_50",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="50-day EMA",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ema_200",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="200-day EMA",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ema_trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BULLISH", "Bullish (50 > 200)"),
                            ("BEARISH", "Bearish (50 < 200)"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bb_upper",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bb_middle",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bb_lower",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bb_position",
                    models.CharField(
                        blank=True, help_text="Price position vs BB", max_length=20
                    ),
                ),
                (
                    "support_level_1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Strongest support",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "support_level_2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "support_level_3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "resistance_level_1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Strongest resistance",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "resistance_level_2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "resistance_level_3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_history",
                    models.JSONField(
                        blank=True,
                        help_text="Last 180 days: [{date, open, high, low, close, volume}]",
                        null=True,
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["stock"],
            },
        ),
        migrations.AlterModelOptions(
            name="signal",
            options={"ordering": ["-quality_score", "-generated_at"]},
        ),
        migrations.AddField(
            model_name="signal",
            name="assignment_risk",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Probability of assignment %",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[("A", "A - Excellent"), ("B", "B - Good"), ("C", "C - Fair")],
                help_text="A/B/C based on score",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="options_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Options metrics score (25%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="quality_score",
            field=models.IntegerField(default=0, help_text="Composite score 0-100"),
        ),
        migrations.AddField(
            model_name="signal",
            name="stock_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Stock quality score (40%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="technical_reason",
            field=models.TextField(
                blank=True, help_text="Why this signal was generated"
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="technical_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Technical setup score (35%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="signal_type",
            field=models.CharField(
                choices=[
                    ("CASH_SECURED_PUT", "Cash-Secured Put"),
                    ("COVERED_CALL", "Covered Call"),
                ],
                default="CASH_SECURED_PUT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=100,
                        help_text="Number of shares (typically 100 per contract)",
                    ),
                ),
                (
                    "cost_basis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average cost per share",
                        max_digits=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, help_text="Total position cost", max_digits=12
                    ),
                ),
                (
                    "assigned_date",
                    models.DateField(help_text="Date when put was assigned"),
                ),
                (
                    "assignment_strike",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Strike price of assigned put",
                        max_digits=10,
                    ),
                ),
                (
                    "premium_collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Premium from put sale",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False if shares sold via covered call"
                    ),
                ),
                (
                    "exit_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when covered call was assigned",
                        null=True,
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Call strike price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_profit_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="ibkr.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
