# Generated by Django 5.0.1 on 2026-01-23 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0003_stockindicator_alter_signal_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[("PUT", "Put"), ("CALL", "Call")], max_length=4
                    ),
                ),
                ("strike", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expiry_date", models.DateField()),
                (
                    "contracts",
                    models.IntegerField(default=1, help_text="Number of contracts"),
                ),
                ("entry_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "entry_premium",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Premium collected per share",
                        max_digits=10,
                    ),
                ),
                (
                    "total_premium",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total premium collected",
                        max_digits=10,
                    ),
                ),
                (
                    "entry_stock_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stock price when opened",
                        max_digits=10,
                    ),
                ),
                (
                    "entry_delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed - Bought Back"),
                            ("ASSIGNED", "Assigned"),
                            ("EXPIRED", "Expired Worthless"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "current_premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current premium to close",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("exit_date", models.DateField(blank=True, null=True)),
                (
                    "exit_premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Premium paid to close",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "realized_pl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="ibkr.option",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_positions",
                        to="ibkr.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
