# Generated by Django 5.0.1 on 2026-01-24 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0004_optionposition"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockWheelScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_score",
                    models.IntegerField(
                        default=0, help_text="Total blended score 0-100"
                    ),
                ),
                (
                    "volatility_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Volatility factor (25%)",
                        max_digits=5,
                    ),
                ),
                (
                    "liquidity_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Liquidity factor (20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "technical_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Technical factor (25%)",
                        max_digits=5,
                    ),
                ),
                (
                    "stability_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Stability factor (20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "price_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price level factor (10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        help_text="Letter grade",
                        max_length=1,
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wheel_scores",
                        to="ibkr.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-calculated_at"],
                        name="ibkr_stockw_stock_i_b74db8_idx",
                    )
                ],
            },
        ),
    ]
