# Generated by Django 5.0.1 on 2026-02-07 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0005_stockwheelscore"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("STOCK_PRICE", "Stock Price Alert"),
                            ("OPTION_PREMIUM", "Option Premium Alert"),
                            ("50_PERCENT_PROFIT", "50% Profit Target"),
                            ("ASSIGNMENT_RISK", "Assignment Risk Alert"),
                            ("EXPIRATION_WARNING", "Expiration Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_stock_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Stock price to trigger alert",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "target_premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Option premium to trigger alert",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "trigger_above",
                    models.BooleanField(
                        default=False,
                        help_text="True = alert when price goes above target, False = below",
                    ),
                ),
                (
                    "notification_method",
                    models.CharField(
                        choices=[
                            ("BROWSER", "Browser Push"),
                            ("TELEGRAM", "Telegram"),
                            ("BOTH", "Both"),
                        ],
                        default="BOTH",
                        max_length=10,
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        help_text="Telegram chat ID for notifications",
                        max_length=50,
                    ),
                ),
                (
                    "push_subscription",
                    models.JSONField(
                        blank=True,
                        help_text="Browser push subscription data",
                        null=True,
                    ),
                ),
                ("message", models.TextField(help_text="Alert message to display")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRIGGERED", "Triggered"),
                            ("DISMISSED", "Dismissed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="ibkr.optionposition",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="ibkr.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "alert_type"],
                        name="ibkr_alert_status_8aceef_idx",
                    ),
                    models.Index(
                        fields=["position", "status"],
                        name="ibkr_alert_positio_e7b9ae_idx",
                    ),
                ],
            },
        ),
    ]
