# Generated by Django 5.0.1 on 2026-02-15 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0006_alert"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(help_text="Number of shares held")),
                (
                    "avg_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average cost per share",
                        max_digits=10,
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current market value",
                        max_digits=12,
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unrealized profit/loss",
                        max_digits=12,
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last sync from IBKR",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="ibkr.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Position",
                "verbose_name_plural": "Stock Positions",
                "ordering": ["-market_value"],
            },
        ),
    ]
