# Generated by Django 5.0.1 on 2026-03-17 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0007_stockposition"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoTradeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, help_text="Master on/off switch for auto-trading"
                    ),
                ),
                (
                    "monthly_goal",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000,
                        help_text="Target premium income to collect each calendar month ($)",
                        max_digits=10,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("conservative", "Conservative"),
                            ("moderate", "Moderate"),
                            ("aggressive", "Aggressive"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Auto-Trade Config",
                "verbose_name_plural": "Auto-Trade Config",
            },
        ),
        migrations.CreateModel(
            name="AutoTradeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SELL_PUT", "Sell Cash-Secured PUT"),
                            ("SELL_CALL", "Sell Covered CALL"),
                            ("BUY_TO_CLOSE", "Buy-to-Close"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "strike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("contracts", models.IntegerField(default=0)),
                (
                    "premium_per_contract",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("ibkr_order_id", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("FILLED", "Filled"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Why this action was taken or skipped",
                        max_length=500,
                    ),
                ),
                (
                    "buying_power_before",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "goal_contribution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="$ this trade contributes toward the monthly goal",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_trade_logs",
                        to="ibkr.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto-Trade Log",
                "verbose_name_plural": "Auto-Trade Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AutoTradeStockConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Enable auto-trading for this stock"
                    ),
                ),
                (
                    "max_contracts",
                    models.IntegerField(
                        blank=True,
                        help_text="Max contracts per trade (null = limited only by buying power)",
                        null=True,
                    ),
                ),
                (
                    "dte_min_override",
                    models.IntegerField(
                        blank=True, help_text="Override global min DTE", null=True
                    ),
                ),
                (
                    "dte_max_override",
                    models.IntegerField(
                        blank=True, help_text="Override global max DTE", null=True
                    ),
                ),
                (
                    "delta_min_override",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "delta_max_override",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_trade_config",
                        to="ibkr.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto-Trade Stock Config",
                "verbose_name_plural": "Auto-Trade Stock Configs",
                "ordering": ["stock__ticker"],
            },
        ),
    ]
